name: mpos_bankend
description: A web server built using the shelf package.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  shelf: ^1.1.0
  path: ^1.8.0
  mime: ^1.0.0
  shelf_router: ^1.0.0

dev_dependencies:
  pedantic: ^1.11.0
